[2024-09-11T12:55:29.413+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T12:55:29.613+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptocurrencies_etl.create_table_task manual__2024-09-11T12:55:20.868834+00:00 [queued]>
[2024-09-11T12:55:29.620+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptocurrencies_etl.create_table_task manual__2024-09-11T12:55:20.868834+00:00 [queued]>
[2024-09-11T12:55:29.621+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-11T12:55:29.646+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_table_task> on 2024-09-11 12:55:20.868834+00:00
[2024-09-11T12:55:29.660+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=81) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-11T12:55:29.661+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2024-09-11T12:55:29.666+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cryptocurrencies_etl', 'create_table_task', 'manual__2024-09-11T12:55:20.868834+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpuylutc0k']
[2024-09-11T12:55:29.669+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask create_table_task
[2024-09-11T12:55:29.881+0000] {task_command.py:426} INFO - Running <TaskInstance: cryptocurrencies_etl.create_table_task manual__2024-09-11T12:55:20.868834+00:00 [running]> on host 45283a8215a9
[2024-09-11T12:55:30.127+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cryptocurrencies_etl' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T12:55:20.868834+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T12:55:20.868834+00:00'
[2024-09-11T12:55:30.128+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T12:55:30.434+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T12:55:30.435+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/toRedshift.py", line 23, in create_table_if_not_exists
    cur.execute(create_table_query)
psycopg2.errors.UniqueViolation: duplicate key violates unique constraint "pg_class_relname_nsp_index" (possibly caused by concurrent transaction conflict)

[2024-09-11T12:55:30.464+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=cryptocurrencies_etl, task_id=create_table_task, run_id=manual__2024-09-11T12:55:20.868834+00:00, execution_date=20240911T125520, start_date=20240911T125529, end_date=20240911T125530
[2024-09-11T12:55:30.491+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task create_table_task (duplicate key violates unique constraint "pg_class_relname_nsp_index" (possibly caused by concurrent transaction conflict)
; 85)
[2024-09-11T12:55:30.547+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-11T12:55:30.562+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
